spring:
  datasource:
    password: Albus:Mia70
    url: jdbc:mysql://localhost:3306/filemandb
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show-sql: true
